laser_line_segment_local:
  ros__parameters:
    frame_id: "laser_link"
    scan_topic: "scan"
    show_lines: true
    least_thresh: 0.04
    min_line_length: 1.5
    predict_distance: 0.1
    seed_line_points: 6
    min_line_points: 12
    use_sim_time: False

line_path_compare_node:
  ros__parameters:
    theta_thr: 0.3  # path和直线角度误差
    dis_thr: 1.0    # path和直线距离误差
    wall_lines_topic: "/wall_lines_stamped"
    time_tolerance: 0.2  # 话题时效性误差
    tf_tolerance: 0.1    # tf变换误差

test_compare_node:
  ros__parameters:
    poses: "[[4.0, -5.0],[2.2, -5.0],[2.2, -4.0],[2.2, -3.0],[2.2, -2.0],[4.0, -2.0]]"


