<?xml version="1.0"?>
<package>
  <name>laserline</name>
  <version>0.0.0</version>
  <description>The laserline package</description>

  <maintainer email="ghm@mail.nankai.edu.cn">ghm</maintainer>

  <license>TODO</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <build_depend>diagnostic_updater</build_depend>
  <!-- <build_depend>driver_base</build_depend> -->
  <!-- <build_depend>dynamic_reconfigure</build_depend> -->
  <!-- <build_depend>rosconsole</build_depend> -->
  <build_depend>rclcpp</build_depend>
  <build_depend>rclpy</build_depend>
  <build_depend>sensor_msgs</build_depend>
  <build_depend>std_msgs</build_depend>
  <!-- <build_depend>system</build_depend> -->
  <!-- <build_depend>thread</build_depend> -->
  <!-- <build_depend>message_generation</build_depend> -->
  <!-- <run_depend>message_runtime</run_depend> -->
  <run_depend>diagnostic_updater</run_depend>
  <!-- <run_depend>driver_base</run_depend> -->
  <!-- <run_depend>dynamic_reconfigure</run_depend> -->
  <!-- <run_depend>rosconsole</run_depend> -->
  <run_depend>rclcpp</run_depend>
  <run_depend>rclpy</run_depend>
  <run_depend>sensor_msgs</run_depend>
  <run_depend>std_msgs</run_depend>
  <!-- <run_depend>system</run_depend> -->
  <!-- <run_depend>thread</run_depend> -->


  <!-- The export tag contains other, unspecified, tags -->
  <export>
    <!-- Other tools can request additional information be placed here -->

  </export>
</package>
